/**
	Generated by sails-inverse-model
	Date:Fri Feb 17 2017 18:54:31 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    autoUpdatedAt:false,
    autoCreatedAt:false,
    attributes: {
        dni: {
            type: 'string',
            required: false
        },
        password: {
            type: 'string',
            required: false
        },
        nombre_cliente: {
            type: 'string',
            required: false
        },
        correo: {
            type: 'string',
            required: true,
            unique: true
        },
        telefono: {
            type: 'string',
            required: true
        },
        reservas:{
         collection:'reserva',
         via:'id_cliente'
        }
    }
};
