/**
	Generated by sails-inverse-model
	Date:Fri Feb 17 2017 18:54:31 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id_cliente: {
            type: 'string',
            required: false
        },
        nombre_cliente: {
            type: 'string',
            required: false
        },
        correo: {
            type: 'string',
            required: true
        },
        direccion: {
            type: 'string',
            required: true
        },
        telefono: {
            type: 'string',
            required: true
        }
    }
};