/**
	Generated by sails-inverse-model
	Date:Thu Feb 16 2017 21:24:29 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id_extra_habitacion: {
            type: 'integer',
            required: false
        },
        jacuzzi: {
            type: 'boolean',
            required: true
        },
        vista_al_mar: {
            type: 'boolean',
            required: true
        },
        costo_extra: {
            type: "float",
            required: false
        }
    }
};