/**
	Generated by sails-inverse-model
	Date:Thu Feb 16 2017 21:24:29 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id_habitacion: {
            type: 'integer',
            required: false
        },
        id_extra_habitacion: {
            type: 'integer',
            required: true
        },
        id_tipo_habitacion: {
            type: 'integer',
            required: false
        },
        numero_piso: {
            type: 'integer',
            required: false
        }
    }
};