/**
	Generated by sails-inverse-model
	Date:Sat Feb 18 2017 01:17:36 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id: {
            type: 'integer',
            required: false
        },
        habitacion_habitaciones: {
            type: 'integer',
            required: true
        },
        reserva_reservas: {
            type: 'integer',
            required: true
        }
    }
};