/**
	Generated by sails-inverse-model
	Date:Thu Feb 16 2017 21:24:29 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        fecha_habitacion_huesped: {
            type: 'date',
            required: false
        },
        id_habitacion: {
            type: 'integer',
            required: false
        },
        id_huesped: {
            type: 'string',
            required: false
        }
    }
};