/**
	Generated by sails-inverse-model
	Date:Fri Feb 17 2017 18:54:32 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id_huesped: {
            type: 'string',
            required: false
        },
        id_habitacion: {
            type: 'integer',
            required: false
        },
        nombre_huesped: {
            type: 'string',
            required: false
        },
        dni: {
            type: 'string',
            required: false
        }
    }
};