/**
	Generated by sails-inverse-model
	Date:Thu Feb 16 2017 21:24:29 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id_perfil: {
            type: 'integer',
            required: false
        },
        id_menu: {
            type: 'integer',
            required: false
        },
        desc_perfil: {
            type: 'string',
            required: false
        }
    }
};