/**
	Generated by sails-inverse-model
	Date:Fri Feb 17 2017 18:54:32 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id_reserva: {
            type: 'integer',
            required: false
        },
        id_cliente: {
            type: 'string',
            required: false
        },
        fecha_inicio: {
            type: 'date',
            required: false
        },
        fecha_fin: {
            type: 'date',
            required: false
        },
        costo_total: {
            required: false
        },
        numero_personas: {
            type: 'integer',
            required: false
        }
    }
};