/**
	Generated by sails-inverse-model
	Date:Thu Feb 16 2017 21:24:29 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id_reserva: {
            type: 'integer',
            required: false
        },
        id_usuario: {
            type: 'integer',
            required: false
        },
        id_servicio: {
            type: 'integer',
            required: false
        },
        fecha_inicio: {
            type: 'date',
            required: false
        },
        fecha_fin: {
            type: 'date',
            required: false
        },
        costo_total: {
            type: "float",
            required: false
        },
        numero_personas: {
            type: 'integer',
            required: false
        }
    }
};