/**
	Generated by sails-inverse-model
	Date:Sat Feb 18 2017 01:17:36 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id_reserva: {
            type: 'integer',
            required: true
        },
        id_habitacion: {
            type: 'integer',
            required: true
        },
        id: {
            type: 'integer',
            required: false
        },
        createdat: {
            type: 'datetime',
            required: true
        },
        updatedat: {
            type: 'datetime',
            required: true
        }
    }
};