/**
	Generated by sails-inverse-model
	Date:Fri Feb 17 2017 18:54:32 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    autoUpdatedAt: false,
    autoCreatedAt: false,
    attributes: {
        id_cliente: { //todo
            type: 'string',
            required: false
        },
        fecha_inicio: {
            type: 'date',
            required: false
        },
        fecha_fin: {
            type: 'date',
            required: false
        },
        desayuno: {
            type: 'boolean',
            defaultsTo: false
        },
        costo_total: {
            type: 'float',
            required: false
        },
        huespedes: {
            collection: 'huesped',
            via: 'id_reserva'
        },
        reservas: {
            collection: 'habitacion',
            via: 'habitaciones',
            dominant: true
        },
        id_cliente: {
            model: 'cliente',
            required: true
        }
    }
};
