/**
	Generated by sails-inverse-model
	Date:Thu Feb 16 2017 21:24:29 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id_servicio: {
            type: 'integer',
            required: false
        },
        desayuno: {
            type: 'boolean',
            required: false
        },
        parqueadero: {
            type: 'boolean',
            required: false
        }
    }
};