/**
	Generated by sails-inverse-model
	Date:Thu Feb 16 2017 21:24:29 GMT-0500 (SA Pacific Standard Time)
*/

module.exports = {
    attributes: {
        id_tipo_habitacion: {
            type: 'integer',
            required: false
        },
        numero_camas: {
            type: 'integer',
            required: false
        },
        costo: {
            type: "float",
            required: false
        },
        descripcion: {
            type: 'string',
            required: false
        }
    }
};